# Generated by Django 5.2.8 on 2025-12-14 17:30

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('outlook', 'Outlook Calendar'), ('google', 'Google Calendar')], max_length=20)),
                ('calendar_id', models.CharField(help_text='External calendar ID', max_length=255)),
                ('calendar_name', models.CharField(blank=True, help_text='Display name of the calendar', max_length=255)),
                ('outlook_email', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Email address of the connected Outlook account', null=True)),
                ('access_token_encrypted', models.TextField(help_text='Access token encrypted with password-based key')),
                ('refresh_token_encrypted', models.TextField(blank=True, help_text='Refresh token encrypted with password-based key', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_direction', models.CharField(choices=[('import', 'Import only (Outlook → App)'), ('export', 'Export only (App → Outlook)'), ('bidirectional', 'Bidirectional (Both ways)')], default='bidirectional', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, help_text='Success, Error, etc.', max_length=50)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_syncs', to='families.member')),
            ],
            options={
                'indexes': [models.Index(fields=['member', 'sync_type', 'sync_enabled'], name='events_cale_member__f8532d_idx')],
                'unique_together': {('member', 'sync_type', 'calendar_id')},
            },
        ),
    ]

