# Generated by Django 5.2.8 on 2025-12-19 14:42

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', encrypted_model_fields.fields.EncryptedCharField()),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('location', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_calendar_id', models.CharField(blank=True, help_text='ID from external calendar (Outlook/Google)', max_length=255, null=True)),
                ('external_calendar_type', models.CharField(blank=True, choices=[('outlook', 'Outlook'), ('google', 'Google')], max_length=20, null=True)),
                ('external_calendar_etag', models.CharField(blank=True, help_text='ETag for conflict detection', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='families.member')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='families.family')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['family', 'starts_at'], name='events_even_family__d41b40_idx'), models.Index(fields=['starts_at', 'ends_at'], name='events_even_starts__3365d7_idx'), models.Index(fields=['external_calendar_id', 'external_calendar_type'], name='events_even_externa_5c1888_idx')],
            },
        ),
    ]
