"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY must be set in .env file
SECRET_KEY = os.getenv('SECRET_KEY', '')
if not SECRET_KEY:
    raise ValueError(
        'SECRET_KEY must be set in .env file. '
        'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0,10.0.0.25,kewlkidsorganizermobile.ngrok.app,*.ngrok.app,*.ngrok-free.app').split(',')

# Custom User Model
AUTH_USER_MODEL = 'api.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # Local apps (must come before staticfiles to override runserver)
    'api',
    'families',
    'lists',
    'meals',
    'encryption',
    'documents',
    'events',

    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'encrypted_model_fields',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware should be as high as possible
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL is REQUIRED for development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME', 'kewlkidsorganizer_mobile'),
        'USER': os.getenv('DATABASE_USER', 'kewlkids_user'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
        'HOST': os.getenv('DATABASE_HOST', 'localhost'),
        'PORT': os.getenv('DATABASE_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', '1'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', '1'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': os.getenv('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': os.getenv('JWT_SECRET_KEY', SECRET_KEY),
}

# CORS Settings
# In development, allow all origins for mobile testing
# In production, use specific allowed origins
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
    # Explicitly allow common development origins
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:8081',
        'http://localhost:19000',
        'http://localhost:19006',
        'http://127.0.0.1:8081',
        'http://127.0.0.1:19000',
        'http://127.0.0.1:19006',
    ]
    # Allow credentials for authenticated requests
    CORS_ALLOW_CREDENTIALS = True
    # Allow all headers (needed for Authorization header)
    CORS_ALLOW_HEADERS = [
        'accept',
        'accept-encoding',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
    ]
    # Allow all methods
    CORS_ALLOW_METHODS = [
        'DELETE',
        'GET',
        'OPTIONS',
        'PATCH',
        'POST',
        'PUT',
    ]
else:
    CORS_ALLOWED_ORIGINS = os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:8081,http://localhost:19000,http://localhost:19006'
    ).split(',')
    CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'True') == 'True'
    CORS_ALLOW_HEADERS = [
        'accept',
        'accept-encoding',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
    ]

# Channels Configuration (for WebSockets)
ASGI_APPLICATION = 'config.asgi.application'

# Redis configuration for Channels
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.getenv('REDIS_HOST', 'localhost'), int(os.getenv('REDIS_PORT', '6379')))],
        },
    },
}

# Encryption Settings (for encrypted_model_fields)
# Generate a key with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# IMPORTANT: FERNET_KEY must be set in .env file and must NEVER change after data is encrypted
# Changing this key will make all encrypted data unreadable
FERNET_KEY = os.getenv('FERNET_KEY', '')
if not FERNET_KEY:
    raise ValueError(
        'FERNET_KEY must be set in .env file. '
        'Generate one with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"'
    )
FIELD_ENCRYPTION_KEY = FERNET_KEY

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'coyotecreekphase3@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'qmkdlrdfljvlqojd')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# For development without Redis, use in-memory channel layer:
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     },
# }

# Cache Configuration (for OAuth state management and encryption keys)
# Use Redis if available so session keys and encrypted OAuth tokens
# survive server restarts and work across multiple processes.
USE_REDIS = os.getenv('USE_REDIS', 'True').lower() == 'true'

if USE_REDIS:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            # Use DB 1 for cache (DB 0 is often used by Channels)
            'LOCATION': os.getenv('REDIS_URL', 'redis://localhost:6379/1'),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'oauth-cache',
        }
    }

# OAuth Settings
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI = os.getenv('GOOGLE_REDIRECT_URI', 'http://localhost:8900/api/googledrive/oauth/callback/')

MICROSOFT_CLIENT_ID = os.getenv('MICROSOFT_CLIENT_ID', '')
MICROSOFT_CLIENT_SECRET = os.getenv('MICROSOFT_CLIENT_SECRET', '')
MICROSOFT_REDIRECT_URI = os.getenv('MICROSOFT_REDIRECT_URI', 'http://localhost:8900/api/calendar/outlook/oauth/callback/')

# OneDrive OAuth Settings (can reuse Microsoft settings if same app)
ONEDRIVE_CLIENT_ID = os.getenv('ONEDRIVE_CLIENT_ID', '') or MICROSOFT_CLIENT_ID
ONEDRIVE_CLIENT_SECRET = os.getenv('ONEDRIVE_CLIENT_SECRET', '') or MICROSOFT_CLIENT_SECRET

# Support both development and production redirect URIs
ONEDRIVE_REDIRECT_URI_DEV = os.getenv('ONEDRIVE_REDIRECT_URI_DEV', 'http://localhost:8900/api/onedrive/oauth/callback/')
ONEDRIVE_REDIRECT_URI_PROD = os.getenv('ONEDRIVE_REDIRECT_URI_PROD', '')
ONEDRIVE_REDIRECT_URI_FALLBACK = os.getenv('ONEDRIVE_REDIRECT_URI', 'http://localhost:8900/api/onedrive/oauth/callback/')

# Use PROD URI if available (for ngrok), otherwise use DEV if in DEBUG mode, otherwise fallback
if ONEDRIVE_REDIRECT_URI_PROD:
    ONEDRIVE_REDIRECT_URI = ONEDRIVE_REDIRECT_URI_PROD
elif ONEDRIVE_REDIRECT_URI_DEV and DEBUG:
    ONEDRIVE_REDIRECT_URI = ONEDRIVE_REDIRECT_URI_DEV
else:
    ONEDRIVE_REDIRECT_URI = ONEDRIVE_REDIRECT_URI_FALLBACK

# Google Drive OAuth Settings (can reuse Google settings if same app)
GOOGLEDRIVE_CLIENT_ID = os.getenv('GOOGLEDRIVE_CLIENT_ID', '') or GOOGLE_CLIENT_ID
GOOGLEDRIVE_CLIENT_SECRET = os.getenv('GOOGLEDRIVE_CLIENT_SECRET', '') or GOOGLE_CLIENT_SECRET

# Support both development and production redirect URIs
GOOGLEDRIVE_REDIRECT_URI_DEV = os.getenv('GOOGLEDRIVE_REDIRECT_URI_DEV', 'http://localhost:8900/api/googledrive/oauth/callback/')
GOOGLEDRIVE_REDIRECT_URI_PROD = os.getenv('GOOGLEDRIVE_REDIRECT_URI_PROD', '')
GOOGLEDRIVE_REDIRECT_URI_FALLBACK = os.getenv('GOOGLEDRIVE_REDIRECT_URI', 'http://localhost:8900/api/googledrive/oauth/callback/')

# Use PROD URI if available (for ngrok), otherwise use DEV if in DEBUG mode, otherwise fallback
if GOOGLEDRIVE_REDIRECT_URI_PROD:
    GOOGLEDRIVE_REDIRECT_URI = GOOGLEDRIVE_REDIRECT_URI_PROD
elif GOOGLEDRIVE_REDIRECT_URI_DEV and DEBUG:
    GOOGLEDRIVE_REDIRECT_URI = GOOGLEDRIVE_REDIRECT_URI_DEV
else:
    GOOGLEDRIVE_REDIRECT_URI = GOOGLEDRIVE_REDIRECT_URI_FALLBACK

# Google Photos OAuth Settings (can reuse Google settings if same app)
GOOGLE_PHOTOS_CLIENT_ID = os.getenv('GOOGLE_PHOTOS_CLIENT_ID', '') or GOOGLE_CLIENT_ID
GOOGLE_PHOTOS_CLIENT_SECRET = os.getenv('GOOGLE_PHOTOS_CLIENT_SECRET', '') or GOOGLE_CLIENT_SECRET

# Support both development and production redirect URIs
GOOGLE_PHOTOS_REDIRECT_URI_DEV = os.getenv('GOOGLE_PHOTOS_REDIRECT_URI_DEV', 'http://localhost:8900/api/googlephotos/oauth/callback/')
GOOGLE_PHOTOS_REDIRECT_URI_PROD = os.getenv('GOOGLE_PHOTOS_REDIRECT_URI_PROD', '')
GOOGLE_PHOTOS_REDIRECT_URI_FALLBACK = os.getenv('GOOGLE_PHOTOS_REDIRECT_URI', 'http://localhost:8900/api/googlephotos/oauth/callback/')

# Use PROD URI if available (for ngrok), otherwise use DEV if in DEBUG mode, otherwise fallback
if GOOGLE_PHOTOS_REDIRECT_URI_PROD:
    GOOGLE_PHOTOS_REDIRECT_URI = GOOGLE_PHOTOS_REDIRECT_URI_PROD
elif GOOGLE_PHOTOS_REDIRECT_URI_DEV and DEBUG:
    GOOGLE_PHOTOS_REDIRECT_URI = GOOGLE_PHOTOS_REDIRECT_URI_DEV
else:
    GOOGLE_PHOTOS_REDIRECT_URI = GOOGLE_PHOTOS_REDIRECT_URI_FALLBACK

# OAuth Session Key Lifetime (for caching user encryption keys)
# Session key lifetime: 24 hours (86400 seconds) to match JWT refresh token lifetime
# This ensures the session key persists across JWT refreshes and auto-refreshes on access
OAUTH_SESSION_KEY_LIFETIME = int(os.getenv('OAUTH_SESSION_KEY_LIFETIME', '86400'))  # 24 hours default

