# Generated by Django 5.2.8 on 2025-12-13 19:46

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('_meals_json', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='{}')),
                ('week_start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meal_plans', to='families.member')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='families.family')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('family', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', encrypted_model_fields.fields.EncryptedCharField()),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('_ingredients_json', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='[]')),
                ('_instructions_json', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='[]')),
                ('image_url', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('source_url', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('prep_time_minutes', models.IntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to='families.member')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='families.family')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['family'], name='meals_recip_family__55fdd3_idx')],
            },
        ),
    ]

