# Generated by Django 5.2.8 on 2025-12-13 20:58

import meals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=meals.models.recipe_image_upload_path),
        ),
    ]
