# Generated by Django 5.2.8 on 2025-12-14 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField(help_text='Per-user key encrypted with password')),
                ('key_version', models.IntegerField(default=1, help_text='For key rotation')),
                ('oauth_tokens_require_reconnection', models.BooleanField(default=False, help_text='True if tokens need reconnection after password reset without old password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Encryption Key',
                'verbose_name_plural': 'User Encryption Keys',
                'db_table': 'encryption_userencryptionkey',
            },
        ),
    ]

