# Generated by Django 5.2.8 on 2026-03-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_recurring_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('e_transfer', 'E-Transfer'), ('check', 'Check'), ('other', 'Other')], default='credit_card', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('e_transfer', 'E-Transfer'), ('check', 'Check'), ('other', 'Other')], default='credit_card', max_length=20),
        ),
    ]
