# Generated by Django 5.2.8 on 2026-09-29 00:29

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', encrypted_model_fields.fields.EncryptedCharField()),
                ('quantity', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('unit_price', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('line_total', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='expenses.expense')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['expense', 'order'], name='expenses_ex_expense_322d06_idx')],
            },
        ),
    ]
