# Generated by Django 5.2.8 on 2025-12-12 19:30

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name from react-icons (e.g., 'FaApple', 'FaBreadSlice')", max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='List of keywords for automatic categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_categories', to='families.family')),
            ],
            options={
                'verbose_name_plural': 'grocery categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', encrypted_model_fields.fields.EncryptedCharField()),
                ('description', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('list_type', encrypted_model_fields.fields.EncryptedCharField(choices=[('shopping', 'Shopping List'), ('grocery', 'Grocery List'), ('todo', 'To-Do List'), ('other', 'Other')], default='shopping')),
                ('color', models.CharField(default='#10b981', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lists', to='families.member')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='families.family')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', encrypted_model_fields.fields.EncryptedCharField()),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('quantity', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='families.member')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='lists.grocerycategory')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_items', to='families.member')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to='families.member')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.list')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='grocerycategory',
            index=models.Index(fields=['family', 'order'], name='lists_groce_family__f1c898_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['family'], name='lists_list_family__430816_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'completed'], name='lists_listi_list_id_375c47_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['category'], name='lists_listi_categor_fba31e_idx'),
        ),
    ]
