# Generated by Django 5.2.8 on 2025-12-14 04:22

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedGroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', encrypted_model_fields.fields.EncryptedCharField()),
                ('item_name', encrypted_model_fields.fields.EncryptedCharField()),
                ('quantity', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('recipe_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_grocery_items', to='families.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_grocery_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Completed Grocery Item',
                'verbose_name_plural': 'Completed Grocery Items',
                'ordering': ['-completed_date'],
                'indexes': [models.Index(fields=['user', 'completed_date'], name='lists_compl_user_id_735b0e_idx'), models.Index(fields=['family', 'completed_date'], name='lists_compl_family__bfcdd8_idx'), models.Index(fields=['completed_date'], name='lists_compl_complet_c5a3d5_idx')],
            },
        ),
    ]
