# Generated by Django 5.2.8 on 2025-12-29 19:34

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_completedgroceryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=encrypted_model_fields.fields.EncryptedCharField(choices=[('shopping', 'Shopping List'), ('grocery', 'Grocery List'), ('todo', 'To-Do List'), ('ideas', 'Ideas'), ('other', 'Other')], default='shopping'),
        ),
    ]
