# Generated by Django 5.2.8 on 2025-12-29 22:48

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


def set_list_type_for_existing_records(apps, schema_editor):
    """Set list_type='grocery' for all existing records."""
    CompletedListItem = apps.get_model('lists', 'CompletedListItem')
    CompletedListItem.objects.all().update(list_type='grocery')


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('lists', '0003_alter_list_list_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename the model
        migrations.RenameModel(
            old_name='CompletedGroceryItem',
            new_name='CompletedListItem',
        ),
        # Rename the related_name on ForeignKeys
        migrations.AlterField(
            model_name='completedlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='completedlistitem',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_list_items', to='families.family'),
        ),
        # Add new fields
        migrations.AddField(
            model_name='completedlistitem',
            name='list_type',
            field=models.CharField(choices=[('shopping', 'Shopping List'), ('grocery', 'Grocery List'), ('todo', 'To-Do List'), ('ideas', 'Ideas'), ('other', 'Other')], default='grocery', max_length=20),
        ),
        migrations.AddField(
            model_name='completedlistitem',
            name='notes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedlistitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        # Data migration: set list_type='grocery' for existing records
        migrations.RunPython(set_list_type_for_existing_records, migrations.RunPython.noop),
        # Update verbose names
        migrations.AlterModelOptions(
            name='completedlistitem',
            options={'ordering': ['-completed_date'], 'verbose_name': 'Completed List Item', 'verbose_name_plural': 'Completed List Items'},
        ),
        # Add index on list_type
        migrations.AddIndex(
            model_name='completedlistitem',
            index=models.Index(fields=['list_type'], name='lists_compl_list_ty_0e209c_idx'),
        ),
    ]
