# Generated by Django 5.2.8 on 2026-03-09 01:02

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('lists', '0004_rename_completed_grocery_to_list_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', encrypted_model_fields.fields.EncryptedCharField()),
                ('bullet_style', models.CharField(choices=[('number', 'Number'), ('dot', 'Dot')], default='number', max_length=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RenameIndex(
            model_name='completedlistitem',
            new_name='lists_compl_user_id_2706d0_idx',
            old_name='lists_compl_user_id_735b0e_idx',
        ),
        migrations.RenameIndex(
            model_name='completedlistitem',
            new_name='lists_compl_family__23df82_idx',
            old_name='lists_compl_family__bfcdd8_idx',
        ),
        migrations.RenameIndex(
            model_name='completedlistitem',
            new_name='lists_compl_complet_a24dff_idx',
            old_name='lists_compl_complet_c5a3d5_idx',
        ),
        migrations.AddField(
            model_name='listitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lists.listitem'),
        ),
        migrations.AlterField(
            model_name='completedlistitem',
            name='list_type',
            field=models.CharField(choices=[('shopping', 'Shopping List'), ('grocery', 'Grocery List'), ('todo', 'To-Do List'), ('ideas', 'Ideas'), ('checklist', 'Checklist'), ('other', 'Other')], default='grocery', max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=encrypted_model_fields.fields.EncryptedCharField(choices=[('shopping', 'Shopping List'), ('grocery', 'Grocery List'), ('todo', 'To-Do List'), ('ideas', 'Ideas'), ('checklist', 'Checklist'), ('other', 'Other')], default='shopping'),
        ),
        migrations.AddField(
            model_name='listsection',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lists.list'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.listsection'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['section'], name='lists_listi_section_508dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['parent'], name='lists_listi_parent__bda879_idx'),
        ),
        migrations.AddIndex(
            model_name='listsection',
            index=models.Index(fields=['list', 'order'], name='lists_lists_list_id_37da55_idx'),
        ),
    ]
