# Generated by Django 5.2.8 on 2026-03-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_checklist_sections_and_nesting'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='indent_level',
            field=models.IntegerField(default=0),
        ),
    ]
