# Generated by Django 5.2.8 on 2026-03-28 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_listsection_section_date'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listsection',
            new_name='lists_lists_list_id_5e41f6_idx',
            old_name='lists_lissect_list_dt_ord',
        ),
        migrations.AlterField(
            model_name='listsection',
            name='section_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
