# Generated by Django 5.2.8 on 2025-12-14 17:30

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googledrive_email', encrypted_model_fields.fields.EncryptedCharField(help_text='Email address of the connected Google Drive account')),
                ('access_token_encrypted', models.TextField(help_text='Access token encrypted with password-based key')),
                ('refresh_token_encrypted', models.TextField(blank=True, help_text='Refresh token encrypted with password-based key', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googledrive_syncs', to='families.member')),
            ],
            options={
                'indexes': [models.Index(fields=['member', 'is_active'], name='documents_g_member__d05fbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='GooglePhotosSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googlephotos_email', encrypted_model_fields.fields.EncryptedCharField(help_text='Email address of the connected Google Photos account')),
                ('access_token_encrypted', models.TextField(help_text='Access token encrypted with password-based key')),
                ('refresh_token_encrypted', models.TextField(blank=True, help_text='Refresh token encrypted with password-based key', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googlephotos_syncs', to='families.member')),
            ],
            options={
                'indexes': [models.Index(fields=['member', 'is_active'], name='documents_g_member__c1f308_idx')],
            },
        ),
        migrations.CreateModel(
            name='OneDriveSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onedrive_email', encrypted_model_fields.fields.EncryptedCharField(help_text='Email address of the connected OneDrive account')),
                ('access_token_encrypted', models.TextField(help_text='Access token encrypted with password-based key')),
                ('refresh_token_encrypted', models.TextField(blank=True, help_text='Refresh token encrypted with password-based key', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onedrive_syncs', to='families.member')),
            ],
            options={
                'indexes': [models.Index(fields=['member', 'is_active'], name='documents_o_member__e94f30_idx')],
            },
        ),
    ]
